### PR TITLE
Added a retry function

### PR DESCRIPTION
**Pull request by OscarApeland**
Implements a simple retry as discussed in https://github.com/hyperoslo/Malibu/issues/86

### CODE REVIEW

**Comment by onmyway133** [comment]
@OscarApeland Looks good to me 👍 But we need some tests @OscarApeland @vadymmarkov

**Comment by vadymmarkov** [comment]
I think I would rather add additional `request` method similar to https://github.com/hyperoslo/Malibu/blob/master/Sources/Networking.swift#L137, but with more parameters  like:
```swift
public func request(_ requestConvertible: R, maximumAttempts: Int = 0, retryInterval: TimeInterval = 0.2, queue: DispatchQueue = .main) -> NetworkPromise
```

Then we can call `execute` on this line https://github.com/hyperoslo/Malibu/blob/master/Sources/Networking.swift#L180 if there are some attempts left.

Or do you think a global function is better @onmyway133 @OscarApeland @zenangst ? I'm worried that it's gonna retry even if the first request was cancelled, and it's probably not what we want.

**Comment by onmyway133** [comment]
We have `Promise` based so I prefer chaining free functions

**Comment by OscarApeland** [comment]
My thought behind the global was to enable

    attempt { tiseService.request(serviceRequest).validate() }

 to retry even if validation fails. 

I'm not particularly good at writing tests, would anyone else like to take care of that? 🕺

**Comment by vadymmarkov** [comment]
Do you mean that you prefer to have a global function @onmyway133 ?

**Comment by onmyway133** [comment]
@vadymmarkov Ah, I mean an extension method on Promise, that allows us to chain

**Comment by OscarApeland** [comment]
Like this, @onmyway133 ?

    service.request(.endpoint)
        .retry(upTo: 5)
        .done { response in ... }

**Comment by vadymmarkov** [comment]
I think it should be doable 👍

**Pull request closed without merging**
